housing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('housing_app.urls', namespace='housing_app')),
]

housing_app/urls.py
from django.urls import path
from . import views

app_name = 'housing_app'
urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    # All advertisements page
    path('advertisements/', views.advertisements, name='advertisements'),
    # Specific advertisement page
    path('advertisement/<int:advertisement_id>',
         views.advertisement,
         name='advertisement'
         ),
    # New advertisement creation page
    path('new_advertisement/',
         views.new_advertisement,
         name='new_advertisement'
         ),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    # LogOut page
    path('logout/', views.logout_view, name='logout'),
    # LogIn page
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    # Registration page
    path('register/', views.register, name='register'),
]

housing_app/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Advertisement(models.Model):
    """Advertisement for the sale of real estate"""
    # Real estate type options
    REAL_ESTATE_TYPE = (
        ('room', 'Room'),
        ('apartment', 'Apartment'),
        ('house', 'House'),
        ('storage', 'Storage'),
        ('garage', 'Garage'),
        ('commercial', 'Commercial'),
    )

    title = models.CharField("Advertisement Title", max_length=50)
    real_estate_type = models.CharField(
        "Real Estate Type",
        max_length=10,
        choices=REAL_ESTATE_TYPE
        )
    location = models.CharField("Location", max_length=50, default="Kyiv")
    contact_number = PhoneNumberField(
        "Contact Number",
        max_length=14,
        blank=False
        )
    description = models.TextField("Description", max_length=250, blank=True)
    area = models.FloatField("Area (sq.m.)", default=1.0)
    price = models.FloatField("Price (UAH)", default=0)

    def __str__(self):
        """Returns the string representation of the model"""
        return self.title

users/models.py
from django.db import models

# Create your models here.

housing_app/forms.py
from django import forms
from .models import Advertisement


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = [
            'title',
            'real_estate_type',
            'location',
            'contact_number',
            'description',
            'area',
            'price',
            ]
        labels = {
            'title': 'Title',
            'real_estate_type': 'Real estate type',
            'location': 'Location',
            'contact_number': 'Contact number',
            'description': 'Description',
            'area': 'Area (sq.m.)',
            'price': 'Price (UAH)',
        }

housing_app/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Advertisement
from .forms import AdvertisementForm


def index(request: HttpRequest) -> HttpResponse:
    """Homepage"""
    return render(request, 'housing_app/index.html')


def advertisements(request: HttpRequest) -> HttpResponse:
    """Renders all advertisements"""
    advertisements = Advertisement.objects.all()
    context = {'advertisements': advertisements}
    return render(request, 'housing_app/advertisements.html', context)


def advertisement(request: HttpRequest, advertisement_id: int) -> HttpResponse:
    """Renders specific advertisement by id"""
    advertisement = get_object_or_404(Advertisement, id=advertisement_id)
    context = {'advertisement': advertisement}
    return render(request, 'housing_app/advertisement.html', context)


def new_advertisement(request: HttpRequest) -> HttpResponse:
    """Renders advertisement creation form"""
    if request.method != 'POST':
        form = AdvertisementForm()
    else:
        form = AdvertisementForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('housing_app:advertisements'))
    context = {'form': form}
    return render(request, 'housing_app/new_advertisement.html', context)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def logout_view(request: HttpRequest) -> HttpResponseRedirect:
    """LogOut from web-application"""
    logout(request)
    return HttpResponseRedirect(reverse('housing_app:index'))


def register(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """Register a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1']
                                              )
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('housing_app:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

housing_app/templates/housing_app/advertisement.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  {{ advertisement.title }}
{% endblock tab_title %}

{% block header %}
  {{ advertisement.title }}
{% endblock header %}

{% block content %}

  <div>
    <p>{{ advertisement.real_estate_type }}</p>

    <p>Location: {{ advertisement.location }}</p>
    <p>Contact number: {{ advertisement.contact_number }}</p>
    <p>Price: {{ advertisement.price }} UAH</p>
    <p>Area: {{ advertisement.area }} sq.m.</p>
    <p>
      Description: <br>
      {{ advertisement.description }}
    </p>
  </div>

{% endblock content %}

housing_app/templates/housing_app/advertisements.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  Advertisements
{% endblock tab_title %}

{% block header %}
  Advertisements
{% endblock header %}

{% block content %}

  <div>
    {% for advertisement in advertisements %}
      <div>
        <a href="{% url 'housing_app:advertisement' advertisement_id=advertisement.id %}">
          <p><b>{{ advertisement.title }}</b></p>
        </a>
        <p>{{ advertisement.location }}</p>
        <p>
          <span>{{ advertisement.price }} UAH</span>
          <span>|</span>
          <span>{{ advertisement.area }} sq.m.</span>
        </p>
      </div>
      <p>&nbsp;</p>
    {% empty %}
      <p>No advertisements have been added yet</p>
    {% endfor %}
  </div>

{% endblock content %}

housing_app/templates/housing_app/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>{% block tab_title %}{% endblock %}</title>
  </head>

  <body>
    <table>
      <th>
        <a href="{% url 'housing_app:index' %}">Home</a>
        &nbsp
        <a href="{% url 'housing_app:advertisements' %}">Advertisements</a>
        &nbsp
        <a href="{% url 'housing_app:new_advertisement' %}">New Advertisement</a>

        &nbsp
        {% if user.is_authenticated %}
          <a>Hello, {{ user.username }}</a>
          &nbsp
          <a href="{% url 'users:logout' %}">Log Out</a>
        {% else %}
          <a href="{% url 'users:login' %}">Log In</a>
        {% endif %}
      </th>
    </table>

    <hr/>

    <div>
      <h1>
        {% block header %}
        {% endblock %}
      </h1>

      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

housing_app/templates/housing_app/index.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  Homepage
{% endblock tab_title %}

{% block header %}
  Homepage
{% endblock header %}

{% block content %}
  <p>Some content</p>
{% endblock content %}

housing_app/templates/housing_app/new_advertisement.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  New Advertisement
{% endblock tab_title %}

{% block header %}
  New Advertisement
{% endblock header %}

{% block content %}

  <form action="{% url 'housing_app:new_advertisement' %}" method="post">
    {% csrf_token %}

    <table>
      {{ form.as_table }}
    </table>

    <input type="submit" value="Publish Advertisement">
  </form>

{% endblock content %}

users/templates/users/login.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  Log In
{% endblock tab_title %}

{% block header %}
  Log In
{% endblock header %}

{% block content %}
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}

    <table>
      {{ form.as_table }}
    </table>

    <input type="submit" value="login">
    <input type="hidden" name="next" value="{% url 'housing_app:index' %}"/>
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "housing_app/base.html" %}

{% block tab_title %}
  Register
{% endblock tab_title %}

{% block header %}
  Register
{% endblock header %}

{% block content %}
  <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}

    <table>
      {{ form.as_table }}
    </table>

    <input type="submit" value="register">
    <input type="hidden" name="next" value="{% url 'housing_app:index' %}"/>
  </form>
{% endblock content %}